"""empty message

Revision ID: 1bfc7b19a43b
Revises: 
Create Date: 2025-09-26 14:51:46.088302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfc7b19a43b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('badge', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entrance_time', sa.Time(), nullable=False),
    sa.Column('exit_time', sa.Time(), nullable=False),
    sa.Column('work_with', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_with'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('entrance_time', sa.Time(), nullable=False),
    sa.Column('exit_time', sa.Time(), nullable=False),
    sa.Column('is_released', sa.String(length=30), nullable=False),
    sa.Column('reseaon_of_releasing', sa.String(), nullable=True),
    sa.Column('mission_kind', sa.String(), nullable=True),
    sa.Column('mission_time', sa.Time(), nullable=True),
    sa.Column('overtime_work', sa.Float(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('fname_after_deleting', sa.String(length=50), nullable=False),
    sa.Column('lname_after_deleting', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('military_guys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badg', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normal_guys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normal_guys')
    op.drop_table('military_guys')
    op.drop_table('employee_info')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('employees')
    # ### end Alembic commands ###
